#one of the issuers defined in issuer-letsencrypt. currently letsencrypt-staging and letsencrypt-prod
TLS_CERTIFICATE_ISSUER: "letsencrypt-staging"
# only needs to be set
K8S_NAMESPACE: "phaidra-dev"
# phaidra hostname -- set to name (or IP address) that you use in your browser to access PHAIDRA
PHAIDRA_HOSTNAME: "phaidra.example.com"
# phaidra server admin email address (for webserver configuration)
PHAIDRA_ADMIN_EMAIL: "you@example.com"
# IP addresses/ranges separated by blank spaces, that are allowed to access to phaidra admin pages (user management, grafana, databases,...).
ADMIN_IP_LIST: "127.0.0.1"
# IP address of your loadbalancer pod (needed for client IP detection), single IP or range
LOAD_BALANCER_IP: "10.1.0.0/24"
# Header to use for original client ip detection
SOURCE_CLIENT_IP_HEADER: "X-Forwarded-For"
# name of the mariadb database used by phaidra-api
PHAIDRADB: "phaidradb"
# name of the mariadb database used by fedora
FEDORADB: "fedoradb"
# name of the mariadb database user
MARIADB_PHAIDRA_USER: "phaidra"
# name of the mongodb database user
MONGODB_PHAIDRA_USER: "phaidra"
# openldap admin username
LDAP_ADMIN_USERNAME: "admin"
# openldap port number
LDAP_PORT_NUMBER: "1389"
# openldap root
LDAP_ROOT: "dc=example,dc=org"
# ldap domain for ldap account manager
LDAP_DOMAIN: "example.org"
# ldap user dn for ldap account manager
LDAP_USERS_DN: "ou=people,dc=example,dc=org"
# ldap group dn for ldap account manager
LDAP_GROUPS_DN: "ou=groups,dc=example,dc=org"
# ldap admin cn for ldap account manager
LDAP_USER: "cn=admin,dc=example,dc=org"
# ldap server adress for ldap account manager
LDAP_SERVER: "ldap://openldap-service:1389"
# fedora admin username
FEDORA_ADMIN_USER: "fedoraAdmin"
# api mountpoint of fedora data directory
FEDORA_OCFL_ROOT: "/mnt/fedora/data/ocfl-root"
# set to empty quoted string on a production setup
PHAIDRA_PORTSTUB: ""
# set to empty quoted string on a production setup
PHAIDRA_HOSTPORT: ""
# api host name for internal ui-api-communication
PHAIDRA_API_HOST_INTERNAL: "api-service"
# set to "https" on a production setup
OUTSIDE_HTTP_SCHEME: "http"
# phaidra admin user
PHAIDRA_ADMIN_USER: "phaidraAdmin"
# agent-libvips image conversion interval in seconds
IMAGE_CONVERSION_INTERVAL: "5"
# solr admin user
SOLR_USER: "phaidra"
# phaidra primary color
PHAIDRA_PRIMARY_COLOR: "#008080"
# chronos database dumps pvc size & type
CHRONOS_DB_DUMP_PVC_SIZE: "100Mi"
CHRONOS_DB_DUMP_PVC_TYPE: "cephfs-fspool-cluster"
# chronos oai logs pvc size & type
CHRONOS_OAI_LOGS_PVC_SIZE: "100Mi"
CHRONOS_OAI_LOGS_PVC_TYPE: "cephfs-fspool-cluster"
# chronos sitemaps pvc size & type
CHRONOS_SITEMAPS_PVC_SIZE: "100Mi"
CHRONOS_SITEMAPS_PVC_TYPE: "cephfs-fspool-cluster"
# dbgate pvc size & type
DBGATE_PVC_SIZE: "100Mi"
DBGATE_PVC_TYPE: "rbd-storagepool-cluster"
# fedora pvc size & type
FEDORA_PVC_SIZE: "100Mi"
FEDORA_PVC_TYPE: "cephfs-fspool-cluster"
# loki pvc size & type
LOKI_PVC_SIZE: "100Mi"
LOKI_PVC_TYPE: "cephfs-fspool-cluster"
# mariadb-fedora pvc size & type
MARIADB_FEDORA_PVC_SIZE: "1Gi"
MARIADB_FEDORA_PVC_TYPE: "rbd-storagepool-cluster"
# mariadb-phaidra pvc size & type
MARIADB_PHAIDRA_PVC_SIZE: "1Gi"
MARIADB_PHAIDRA_PVC_TYPE: "rbd-storagepool-cluster"
# mongodb-phaidra pvc size & type
MONGODB_PHAIDRA_PVC_SIZE: "1Gi"
MONGODB_PHAIDRA_PVC_TYPE: "rbd-storagepool-cluster"
# openldap pvc size & type
OPENLDAP_PVC_SIZE: "100Mi"
OPENLDAP_PVC_TYPE: "cephfs-fspool-cluster"
# agent-libvips pvc size & type
AGENT_LIBVIPS_PVC_SIZE: "100Mi"
AGENT_LIBVIPS_PVC_TYPE: "cephfs-fspool-cluster"
# solr pvc size & type
SOLR_PVC_SIZE: "100Mi"
SOLR_PVC_TYPE: "cephfs-fspool-cluster"
# grafana admin credentials
GF_SECURITY_ADMIN_USER: "phaidra"
# grafana pvc size & type
GRAFANA_PVC_SIZE: "100Mi"
GRAFANA_PVC_TYPE: "cephfs-fspool-cluster"

s3:
  S3_CACHE_SIZE: 500000000
  S3_CACHE_TOPDIR: "/mnt/derivates-images"

# fedora for agent-libvips s3
FEDORA_HOST: fedora-service
FEDORA_PROTOCOL: http
FEDORA_PORT: 8080
