apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    phaidra.app: agent-libvips
  name: agent-libvips-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: "{{ .Values.AGENT_LIBVIPS_PVC_TYPE }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.AGENT_LIBVIPS_PVC_SIZE }}"
status: {}
