apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-libvips-config
data:
  agent-libvips_conf.yml: |
    agent-libvips:
      mongodb:
        host:                  'mongodb-phaidra-service'
        ## authentication database
        db_name:               'admin'
        ## active database
        database:              'paf_mongodb'
        username:              'phaidra'
        password:              'phaidra'
        col:                   'jobs'
        activity:              'activity'
      store:                 '/mnt/derivates-images'
      temp_path:             '/tmp'

