apiVersion: v1
kind: ConfigMap
metadata:
  name: cameltoolbox-config
data:
  # https://github.com/helm/helm/issues/4026#issuecomment-1256609433
  # use like `helm template -s templates/cameltoolbox-configmap.yaml . --debug --set fixityhandler=$(cat ../../scripts/fixity_handler.sh | base64 -w0)`
  fixity_handler: |
    {{ .Values.fixityhandler | b64dec | nindent 4 }}
