apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ldapaccountmanager-imagestream
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: iipsrv-imagestream
spec:
  lookupPolicy:
    local: false
